# Generated by Django 3.2.9 on 2021-12-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='workunit',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.workday'),
        ),
    ]
